const DEPARTMENTS = [
  { id: 'all', name: 'All Departments', icon: 'grid' },
  { id: 'capital-markets', name: 'Capital Markets', icon: 'trending-up' },
  { id: 'retail-advisory', name: 'Retail Advisory', icon: 'shopping-bag' },
  { id: 'property-management', name: 'Property Management', icon: 'building' },
  { id: 'leasing', name: 'Leasing & Brokerage', icon: 'handshake' },
  { id: 'valuation', name: 'Valuation & Advisory', icon: 'bar-chart' },
  { id: 'research', name: 'Research & Analysis', icon: 'search' },
  { id: 'corporate', name: 'Corporate Solutions', icon: 'briefcase' },
];

const CATEGORIES = [
  { id: 'writing',       name: 'Writing & Communication' },
  { id: 'analysis',      name: 'Analysis & Research' },
  { id: 'proposal',      name: 'Proposal Development' },
  { id: 'international', name: 'International Coordination' },
  { id: 'client-prep',   name: 'Client Preparation' },
];

const LABEL_TYPES = {
  'frequently-used': { text: 'Frequently Used', color: 'blue' },
  'high-impact': { text: 'High Impact', color: 'green' },
  'under-5': { text: 'Under 5 mins', color: 'purple' },
};

const PROMPTS = [
  // ─── GENERAL / TRANSVERSAL ───────────────────────────────────────────────
  {
    id: 1,
    title: 'Executive Summary',
    category: 'writing',
    tool: 'copilot',
    departments: ['all'],
    labels: ['frequently-used', 'high-impact', 'under-5'],
    prompt: `Write a concise executive summary (max 250 words) for the following document:\n\n[PASTE DOCUMENT HERE]\n\nStructure it as:\n• Situation: What is the context?\n• Key Findings: Top 3 data points or insights\n• Recommendation: Clear next step\n• Expected Outcome: Measurable result\n\nTone: Professional, direct, senior-leadership ready.`,
    useCase: {
      team: 'Retail Advisory',
      task: 'Executive Summary',
      result: 'Reduced drafting time by 30%',
    },
  },
  {
    id: 2,
    title: 'Professional Email Draft',
    category: 'writing',
    tool: 'copilot',
    departments: ['all'],
    labels: ['frequently-used', 'under-5'],
    prompt: `Draft a professional email based on the following context:\n\nPurpose: [e.g. follow-up after site visit / proposal submission / meeting request]\nRecipient: [Client name / Role]\nKey message: [What do you need to convey or ask?]\nTone: [Formal / Warm-professional / Urgent]\n\nKeep it under 150 words. Include a clear subject line. End with a specific call-to-action.`,
    useCase: null,
  },
  {
    id: 3,
    title: 'Meeting Notes → Action Items',
    category: 'proposal',
    tool: 'copilot',
    departments: ['all'],
    labels: ['frequently-used', 'under-5'],
    prompt: `Convert the following meeting notes into a structured summary:\n\n[PASTE NOTES HERE]\n\nOutput format:\n**Date & Attendees:**\n**Key Decisions Made:**\n**Action Items:** (Owner | Task | Deadline)\n**Open Questions:**\n\nBe concise. Do not invent information not present in the notes.`,
    useCase: null,
  },
  {
    id: 4,
    title: 'Data Insight Narrative',
    category: 'analysis',
    tool: 'claude',
    departments: ['all'],
    labels: ['high-impact'],
    prompt: `I have the following dataset / metrics:\n\n[PASTE DATA OR TABLE]\n\nWrite a 3-paragraph narrative analysis that:\n1. Explains the trend in plain language\n2. Identifies 2-3 notable outliers or inflection points\n3. Suggests what this means for decision-making\n\nAvoid jargon. Write for a non-technical business audience.`,
    useCase: null,
  },
  {
    id: 5,
    title: 'Presentation Slide Outline',
    category: 'proposal',
    tool: 'copilot',
    departments: ['all'],
    labels: ['frequently-used', 'high-impact'],
    prompt: `Create a slide-by-slide outline for a [X]-minute presentation on the following topic:\n\nTopic: [e.g. Q3 Market Outlook / Property Portfolio Review]\nAudience: [e.g. C-suite / Client / Internal team]\nGoal: [e.g. Secure approval / Inform / Persuade]\n\nFor each slide provide:\n- Slide title\n- 3 bullet points of content\n- Suggested visual (chart type, image, icon)\n\nKeep the narrative arc: Problem → Evidence → Solution → Call to action.`,
    useCase: null,
  },
  {
    id: 6,
    title: 'SWOT Analysis',
    category: 'international',
    tool: 'claude',
    departments: ['all'],
    labels: ['high-impact'],
    prompt: `Perform a SWOT analysis for the following:\n\n[DESCRIBE THE ASSET / MARKET / STRATEGY]\n\nFor each quadrant (Strengths, Weaknesses, Opportunities, Threats) provide:\n- 4-5 specific, evidence-based points\n- One standout factor that deserves immediate attention\n\nConclude with a one-paragraph strategic recommendation.`,
    useCase: null,
  },

  // ─── CAPITAL MARKETS ─────────────────────────────────────────────────────
  {
    id: 7,
    title: 'Investment Memo Draft',
    category: 'proposal',
    tool: 'claude',
    departments: ['capital-markets'],
    labels: ['high-impact'],
    prompt: `Draft an investment memorandum for the following asset:\n\nAsset: [Property name, type, location]\nAsk Price: [Amount]\nKey Financials: [Cap rate, NOI, occupancy]\nInvestment Thesis: [Why is this compelling?]\n\nStructure:\n1. Executive Overview\n2. Market Context (local CRE dynamics)\n3. Asset Quality & Risk Factors\n4. Financial Summary\n5. Recommended Position\n\nWrite for a sophisticated institutional investor. Be factual; flag assumptions clearly.`,
    useCase: {
      team: 'Capital Markets',
      task: 'Investment Memo',
      result: 'Cut memo prep time from 4 hours to 45 minutes',
    },
    detail: {
      timeSaved: '45 min',
      timeSavedContext: 'Capital Markets advisors cut memo prep from ~4 hours to under 45 minutes using this as a starting framework.',
      whenToUse: [
        'After a site visit, when you need structured documentation before an investment committee meeting.',
        'When a client or senior stakeholder requests a deal summary on short notice.',
        'Preparing pitch materials for a new deal and need a professional first draft quickly.',
        'When you want a consistent memo structure across your team\'s deal documentation.',
      ],
      tips: [
        { title: 'Be specific in the brackets', body: 'The more detail you give — exact financials, tenant name, lease expiry — the less editing the output needs. Vague inputs produce generic memos.' },
        { title: 'Treat the output as a first draft', body: 'Always verify every figure, yield, and market claim before sending. AI can generate plausible-sounding data it was never given.' },
        { title: 'Add your market read after', body: 'The Market Context section benefits most from your own judgement. Layer in your on-the-ground insight after generation to make it uniquely yours.' },
      ],
    },
  },
  {
    id: 8,
    title: 'Comparable Transaction Analysis',
    category: 'analysis',
    tool: 'ellis',
    departments: ['capital-markets', 'valuation'],
    labels: ['frequently-used', 'high-impact'],
    prompt: `Analyze the following comparable transactions and benchmark them against my subject property:\n\nSubject Property: [Describe]\nComps (paste table or list):\n[PASTE COMPS DATA]\n\nProvide:\n- Price per SF / Cap rate range\n- Market positioning of subject property (above / at / below market)\n- 3 adjustments to consider\n- Suggested pricing narrative for client discussion`,
    useCase: null,
  },
  {
    id: 9,
    title: 'Investor Q&A Prep',
    category: 'client-prep',
    tool: 'claude',
    departments: ['capital-markets'],
    labels: ['frequently-used', 'under-5'],
    prompt: `I am presenting the following deal to investors:\n\n[Brief deal description]\n\nGenerate the 10 most likely tough questions investors will ask, covering:\n- Financial risk\n- Market conditions\n- Exit strategy\n- Competitive alternatives\n\nFor each question, provide a concise, confident answer (2-3 sentences). Flag any question where I should have backup data ready.`,
    useCase: null,
  },

  // ─── RETAIL ADVISORY ─────────────────────────────────────────────────────
  {
    id: 10,
    title: 'Retail Market Snapshot',
    category: 'analysis',
    tool: 'ellis',
    departments: ['retail-advisory'],
    labels: ['frequently-used', 'high-impact'],
    prompt: `Write a retail market snapshot for the following area:\n\nLocation: [City / Submarket]\nFocus: [High street / Shopping center / Mixed-use]\nData available: [PASTE any metrics, vacancy rates, footfall data]\n\nOutput:\n- Market headline (1 sentence)\n- Key trends (3 bullets)\n- Occupier demand signals\n- Risk factors\n- Outlook (6-12 month)\n\nWrite in a tone appropriate for a client-facing market report.`,
    useCase: {
      team: 'Retail Advisory',
      task: 'Market Snapshot',
      result: 'Reports delivered 2 days faster per quarter',
    },
  },
  {
    id: 11,
    title: 'Retailer Site Assessment',
    category: 'client-prep',
    tool: 'ellis',
    departments: ['retail-advisory'],
    labels: ['high-impact'],
    prompt: `Assess the following site for a retail occupier:\n\nOccupier type: [e.g. Fast fashion / QSR / Luxury]\nSite: [Address, SF, configuration]\nCatchment data: [Population, footfall, competing anchors]\n\nProvide:\n- Fit score (High / Medium / Low) with rationale\n- Top 3 positive factors\n- Top 3 risks\n- Lease recommendation (rent range, key clauses to negotiate)`,
    useCase: null,
  },
  {
    id: 12,
    title: 'Tenant Mix Strategy',
    category: 'analysis',
    tool: 'claude',
    departments: ['retail-advisory', 'property-management'],
    labels: ['high-impact'],
    prompt: `Develop a tenant mix strategy for the following retail asset:\n\nAsset: [Type, size, location]\nCurrent vacancy: [%]\nExisting anchors: [List]\nTarget customer: [Demographics]\n\nRecommend:\n- Ideal category breakdown (% by GLA)\n- 5-8 target tenants per category (realistic operators for this market)\n- 1 "experience" concept to drive footfall\n- Phasing priority (what to fill first and why)`,
    useCase: null,
  },

  // ─── PROPERTY MANAGEMENT ─────────────────────────────────────────────────
  {
    id: 13,
    title: 'Maintenance Request Response',
    category: 'client-prep',
    tool: 'copilot',
    departments: ['property-management'],
    labels: ['frequently-used', 'under-5'],
    prompt: `Draft a professional response to the following tenant maintenance request:\n\nRequest: [Describe the issue]\nStatus: [Received / Scheduled / In progress / Resolved]\nExpected resolution: [Date or timeframe]\n\nTone: Empathetic, clear, professional. Reassure the tenant, state the next step, and provide a contact for follow-up. Max 100 words.`,
    useCase: null,
  },
  {
    id: 14,
    title: 'Monthly Property Report',
    category: 'proposal',
    tool: 'copilot',
    departments: ['property-management'],
    labels: ['frequently-used', 'high-impact'],
    prompt: `Write a monthly property management report for the owner using the following data:\n\nProperty: [Name, type]\nPeriod: [Month/Year]\nOccupancy: [%]\nRent collected: [% and amount]\nMaintenance items: [List open and closed]\nIncidents: [Any notable events]\n\nFormat:\n- Performance Summary (3 bullets)\n- Financial Snapshot\n- Operations Update\n- Upcoming Actions\n\nTone: Transparent, factual, owner-focused.`,
    useCase: {
      team: 'Property Management',
      task: 'Monthly Owner Report',
      result: 'Standardized reporting across 40+ assets',
    },
  },
  {
    id: 15,
    title: 'Lease Renewal Negotiation Brief',
    category: 'proposal',
    tool: 'claude',
    departments: ['property-management', 'leasing'],
    labels: ['high-impact'],
    prompt: `Prepare a negotiation brief for the following lease renewal:\n\nTenant: [Name, sector]\nCurrent lease: [Expiry, rent, SF]\nMarket rent estimate: [Range]\nTenant payment history: [Good / Issues / Arrears]\nStrategic priority: [Retain / Negotiate increase / Let expire]\n\nOutput:\n- Our opening position\n- Minimum acceptable terms\n- 3 concessions we can offer\n- Likely tenant objections + rebuttals\n- Walk-away scenario`,
    useCase: null,
  },

  // ─── LEASING & BROKERAGE ─────────────────────────────────────────────────
  {
    id: 16,
    title: 'Property Listing Description',
    category: 'writing',
    tool: 'copilot',
    departments: ['leasing'],
    labels: ['frequently-used', 'under-5'],
    prompt: `Write a compelling property listing description for the following:\n\nProperty: [Address, type, SF]\nKey features: [Floor plate, amenities, spec, transport]\nTarget occupier: [Tech company / Law firm / etc.]\nAsking rent: [£/$/€ per SF]\n\nWrite two versions:\n1. Short (50 words) — for portals and social media\n2. Long (150 words) — for brochures and marketing packs\n\nHighlight unique selling points first. No filler phrases like "rare opportunity."`,
    useCase: null,
  },
  {
    id: 17,
    title: 'Client Requirements Brief',
    category: 'client-prep',
    tool: 'copilot',
    departments: ['leasing'],
    labels: ['frequently-used', 'under-5'],
    prompt: `Convert the following client conversation notes into a structured requirements brief:\n\n[PASTE NOTES / TRANSCRIPT]\n\nOutput:\n- Occupier profile\n- Space requirements (SF range, configuration)\n- Location priorities (must-have vs. nice-to-have)\n- Budget / rent sensitivity\n- Key decision criteria\n- Timeline & process\n- Red flags or sensitivities to be aware of\n\nThis brief will be shared with the search team.`,
    useCase: null,
  },
  {
    id: 18,
    title: 'Deal Pipeline Status Update',
    category: 'proposal',
    tool: 'copilot',
    departments: ['leasing', 'capital-markets'],
    labels: ['frequently-used'],
    prompt: `Write a pipeline status update for the following deals:\n\n[PASTE DEAL LIST WITH STAGE INFO]\n\nFor each deal provide a one-line status update in this format:\n[Property] — [Stage] — [Next action] — [Probability %] — [Expected close]\n\nThen write a 3-bullet summary for leadership highlighting:\n- Deals most likely to close this quarter\n- Deals at risk\n- Any resource or decision needs`,
    useCase: null,
  },

  // ─── VALUATION & ADVISORY ────────────────────────────────────────────────
  {
    id: 19,
    title: 'Valuation Rationale Summary',
    category: 'writing',
    tool: 'claude',
    departments: ['valuation'],
    labels: ['high-impact'],
    prompt: `Summarise the valuation rationale for the following property:\n\nProperty: [Type, location, size]\nValuation: [Amount]\nMethod used: [Income / Comparable / Cost]\nKey assumptions: [Yield, ERV, vacancy, capex]\n\nWrite a 200-word rationale suitable for a valuation certificate or client letter. Cover:\n- Market context\n- Method justification\n- Key value drivers\n- Caveats and risk factors`,
    useCase: null,
  },
  {
    id: 20,
    title: 'Market Yield Analysis',
    category: 'international',
    tool: 'ellis',
    departments: ['valuation', 'capital-markets'],
    labels: ['high-impact'],
    prompt: `Analyse current market yields for the following sector and geography:\n\nSector: [Office / Industrial / Retail / Residential]\nGeography: [City / Region]\nAvailable data: [PASTE any benchmark data]\n\nProvide:\n- Current prime yield vs. secondary yield spread\n- Direction of travel (hardening / softening / stable)\n- Key drivers of yield movement\n- Comparable markets for context\n- Outlook narrative (100 words)`,
    useCase: null,
  },

  // ─── RESEARCH & ANALYSIS ─────────────────────────────────────────────────
  {
    id: 21,
    title: 'Market Research Report Section',
    category: 'analysis',
    tool: 'ellis',
    departments: ['research'],
    labels: ['frequently-used', 'high-impact'],
    prompt: `Write a research report section on the following topic:\n\nTopic: [e.g. Logistics & Industrial Market — Q2 2025]\nGeography: [Region/City]\nKey data points I have: [PASTE DATA]\nAudience: [Investors / Occupiers / Internal]\n\nStructure:\n- Headline trend (1 powerful sentence)\n- Supply & demand dynamics\n- Rental/pricing movement\n- Leasing activity highlights\n- Outlook\n\n300-400 words. Data-led, minimal opinion unless clearly flagged as analysis.`,
    useCase: {
      team: 'Research',
      task: 'Quarterly Market Report',
      result: 'First draft ready in 20 minutes vs. 2 hours',
    },
  },
  {
    id: 22,
    title: 'Competitor Intelligence Brief',
    category: 'international',
    tool: 'claude',
    departments: ['research'],
    labels: ['high-impact'],
    prompt: `Compile a competitor intelligence brief based on the following sources:\n\n[PASTE news articles, press releases, or public data]\n\nOutput:\n- Summary of key competitor moves (3-5 bullets)\n- Strategic implications for our business\n- Market opportunities their activity opens up\n- Recommended response or monitoring actions\n\nFocus on what matters commercially, not just activity volume.`,
    useCase: null,
  },

  // ─── CORPORATE SOLUTIONS ─────────────────────────────────────────────────
  {
    id: 23,
    title: 'Workplace Strategy Summary',
    category: 'writing',
    tool: 'claude',
    departments: ['corporate'],
    labels: ['high-impact'],
    prompt: `Summarize a workplace strategy recommendation for the following client:\n\nCompany: [Sector, headcount, current footprint]\nObjectives: [Cost reduction / Collaboration / Flexibility]\nData: [Occupancy data, employee survey results if available]\n\nRecommend:\n- Optimal space model (HQ + hub / fully flexible / etc.)\n- Target SF range and rationale\n- Key design principles\n- Implementation phasing\n- Expected outcomes (quantified where possible)`,
    useCase: {
      team: 'Corporate Solutions',
      task: 'Workplace Strategy',
      result: 'Proposal win rate improved; clients cited clarity of recommendation',
    },
  },
  {
    id: 24,
    title: 'Portfolio Rationalisation Analysis',
    category: 'analysis',
    tool: 'claude',
    departments: ['corporate'],
    labels: ['high-impact'],
    prompt: `Analyse the following real estate portfolio for rationalisation opportunities:\n\n[PASTE portfolio list: location, SF, lease expiry, cost, utilisation %]\n\nIdentify:\n- Assets to exit (low utilisation + high cost or near expiry)\n- Assets to right-size\n- Assets to retain / invest in\n- Estimated savings from recommended changes\n\nPresent findings in a decision matrix format. Flag any dependencies (e.g. key talent locations, contractual constraints).`,
    useCase: null,
  },
  {
    id: 25,
    title: 'Client Proposal Introduction',
    category: 'writing',
    tool: 'claude',
    departments: ['corporate', 'leasing', 'capital-markets'],
    labels: ['frequently-used'],
    prompt: `Write the introduction section for a client proposal:\n\nClient: [Company name, sector]\nOur service offering: [What we are proposing]\nClient's stated challenge: [What they told us]\nOur differentiator: [Why us over competitors]\n\n150 words max. Open with the client's challenge (not our credentials). Show we understand their world. End with a bridge sentence to the rest of the proposal.`,
    useCase: null,
  },
];

const USE_CASES = [
  {
    id: 1,
    team: 'Retail Advisory',
    task: 'Executive Summary',
    result: 'Reduced drafting time by 30%',
    detail: 'The team used the Executive Summary prompt on weekly deal memos. What previously required a 45-minute drafting session became a 10-minute review-and-refine workflow.',
    metric: '30%',
    metricLabel: 'time saved',
    promptId: 1,
  },
  {
    id: 2,
    team: 'Capital Markets',
    task: 'Investment Memorandum',
    result: 'Cut prep time from 4 hours to 45 minutes',
    detail: 'Advisors used the Investment Memo prompt as a starting framework, then layered in proprietary data. Client-ready memos went out same day instead of the following morning.',
    metric: '5×',
    metricLabel: 'faster output',
    promptId: 7,
  },
  {
    id: 3,
    team: 'Property Management',
    task: 'Monthly Owner Reports',
    result: 'Standardised reporting across 40+ assets',
    detail: 'The PM team templated the Monthly Property Report prompt with asset-specific data fields. Reports are now consistent in format and tone, improving owner satisfaction scores.',
    metric: '40+',
    metricLabel: 'assets standardised',
    promptId: 14,
  },
  {
    id: 4,
    team: 'Research',
    task: 'Quarterly Market Report',
    result: 'First draft ready in 20 minutes vs. 2 hours',
    detail: 'Research analysts run data through the Market Research Report Section prompt to generate a structured first draft. Editing a draft is 6× faster than writing from scratch.',
    metric: '20 min',
    metricLabel: 'first draft',
    promptId: 21,
  },
  {
    id: 5,
    team: 'Corporate Solutions',
    task: 'Workplace Strategy Proposal',
    result: 'Higher proposal win rate',
    detail: 'Account managers used the Workplace Strategy Summary prompt to sharpen recommendations before client presentations. Clients consistently noted the clarity and structure of proposals.',
    metric: '↑ Win rate',
    metricLabel: 'proposal quality',
    promptId: 23,
  },
];
